### ISSUE TITLE
Enable EAB for ACME CA Handler

### ISSUE THREAD

**Issue by invis-z** [grindsa/acme2certifier#166]
Is it possible to add EAB profiling to the ACME CA handler? 

Personally I am using a self hosted Smallstep CA in my LAN and I wish to use this project in front of it to add EAB support. Apart from my use case, this should also be handy to be able to use different CAs based on the EAB profile. For example, `key_01` to **Let's Encrypt** with only _domain1.com_ allowed and `key_02` to **ZeroSSL** for the rest.

Thanks for the amazing project!

**Comment by webprofusion-chrisc** [comment]
Slightly off topic but does self-hosted smallstep not already have EAB? https://smallstep.com/blog/acme-eab-overview/

**Comment by grindsa** [comment]
I pushed an [updated handler](https://github.com/grindsa/acme2certifier/blob/devel/examples/ca_handler/acme_ca_handler.py) into the [devel branch](https://github.com/grindsa/acme2certifier/tree/devel). Test-workflows are not updated yet but feel free to give it a try.

I also included [some configuration instructions](https://github.com/grindsa/acme2certifier/blob/devel/docs/acme_ca.md#eab-profiling) hoping they would be helpful to you.

**Comment by grindsa** [comment]
hi again, unfortunately the profiling feature did not work as expected due to some variable names. Fix is included in 78e1e0a32e219523165a83f5ba3d17dea5ba187c. Please use the updated handler and try again

**Comment by grindsa** [comment]
There is an "400 - error message" coming from Smallstep. But this does not necessarily mean that we are behaving correctly.

Does this problem also occur without eab-profiling feature enabled?

BR Joern

**Comment by grindsa** [comment]
Just to keep you updated: I am able to replicate the issue in my setup. 

Here is a quick summary what happens.

It seems you do not have the `acme_account` parameter configured in `acme_srv.cfg`. 
In this case a2c tries to query the account information from Smallstep-CA. This query fails with an "acme:error:malformed" error. 
Due to this erorr a2c will try to create a new account on smallstep-ca which will fail with a 'ConflictError' exception.

Hard to say who is behaving wrong here. Good news is that I have a workaround in mind. Further error handling for such situations needs to be improved. So stay tuned…

**Comment by grindsa** [comment]
Feature made it into [v0.35](https://github.com/grindsa/acme2certifier/releases/tag/0.35). Thus, closing this issue. In case you have comments feel free to reopen...
