### ISSUE TITLE
Suggestion : adding External Account Binding

### ISSUE THREAD

**Issue by Raldoh19** [grindsa/acme2certifier#53]
Hi,
Thank your for sharing your project, it is really nice, I'm using it to ensure communication between acme clients and Microsoft services and it's running smoothly.

I wanted to make a suggestion: adding the possibility of creating external account binding. (according to the RFC 8555 - Section 7.3.4)
This could be very helpful to manage more easily the different ACME Accounts  and also avoid unwanted ACME request to be processed.

**Comment by grindsa** [comment]
Hi, 

I was already thinking about this topic but had to park it due to other priorities.  But let me have a look into it again.

One question.: any idea how to feed to macs to be verified to acme2certifer? Would a text-file be sufficient would you prefer a plugin-based mechanism allowing to write customized validators.

**Comment by grindsa** [comment]
Hi again,

eab is supported starting from release 0.14. Check [eab.md](/grindsa/acme2certifier/blob/master/docs/eab.md) for further information.
